//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaEvertec.core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderProducts
    {
        public int Id { get; set; }
        public int IdOrder { get; set; }
        public string ProductDescription { get; set; }
        public int Quantity { get; set; }
        public decimal ValuePerUnit { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
